title: Résumé | Graham Greenfield
description:  Professional employment history of Graham Greenfield.
url: https://grahamg.github.io/resume
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
